name: Bug Report
description: Report a bug in the package
title: "[Bug]: "
labels:
  - bug
assignees:
  - your-github-username

body:
  - type: markdown
    attributes:
      value: |
        ## 🐞 Bug Report
        Thanks for reporting a bug!
        Please provide **minimal and reproducible** information.
        Issues without reproduction steps may be closed.

  - type: input
    id: package_version
    attributes:
      label: Package Version
      description: Output of `pip show <package-name>` or `pip list`
      placeholder: 1.2.3
    validations:
      required: true

  - type: input
    id: python_version
    attributes:
      label: Python Version
      description: Output of `python --version`
      placeholder: Python 3.12.1
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - macOS
        - Linux
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Clear and concise description of the problem
      placeholder: The function raises an exception when input is empty
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the issue
      placeholder: |
        1. Install the package
        2. Import the module
        3. Call function X with input Y
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: The function should return an empty list
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      placeholder: It raises ValueError
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Minimal Reproducible Code
      description: Paste the smallest code snippet that reproduces the bug
      render: python
      placeholder: |
        from mypackage import my_function

        my_function("")
    validations:
      required: true

  - type: textarea
    id: traceback
    attributes:
      label: Traceback / Error Output
      description: Full traceback if available
      render: shell
      placeholder: |
        Traceback (most recent call last):
        ...
  
  - type: checkboxes
    id: confirmation
    attributes:
      label: Checklist
      options:
        - label: I am using the latest version of the package
          required: true
        - label: I have searched existing issues
          required: true
        - label: I can reproduce this issue reliably
          required: true
